### ISSUE TITLE
NPM start failed on window machine

### ISSUE THREAD

**Issue by naveen-sf** [sourcefuse/react-boilerplate-ts-ui#62]
**Issue Title**: Script "config" not working on Windows environment

**Issue Description**: 

**Expected Behaviour**:
When running the "config" script in the project on a Windows machine, the script should successfully generate a configuration file based on the template, set environment variables, and copy the resulting configuration file to the "public" directory.

**Actual Behaviour**:
The "config" script is currently designed to work on Unix-like systems and is utilising shell commands that are not directly compatible with Windows environments.

**Steps to Reproduce**:
Clone the project repository to a Windows machine.
Run the start script using the provided command:
npm run start

Observe that the script fails to execute as expected due to the use of Unix-specific shell commands.

**Proposed Solution**:
To make the "config" script compatible with Windows environments, the script should be refactored to use cross-platform commands or to handle Windows-specific operations.

**Additional Information**:
Project setup includes a "config" script defined in the "scripts" section of the package.json file.
The script is designed to read environment variables from a .env file, execute a shell script (env.sh), and copy resulting configuration files to the "public" directory.
The provided commands (export, chmod, ./env.sh, cp) are Unix-specific and may not work as expected on Windows machines.

**Environment**:
Operating System: Windows 10
Node.js version: 18.17.0
npm version: 0.38.0
Project repository: https://github.com/sourcefuse/isbc-ui

**Note**:
As of the issue creation date, the script relies on shell commands that might not be directly compatible with Windows. It's recommended to refactor the script to use cross-platform alternatives or provide separate handling for Windows environments.

![image](https://github.com/sourcefuse/react-boilerplate-ts-ui/assets/78717467/b23cdc16-e464-457e-9697-a94ee4195fae)

**Comment by rohit-sourcefuse** [comment]
Here's a proposed solution comment that suggests using the configGenerator.js script as an alternative to the Unix-specific shell commands on Windows environments:

**Proposed Solution:**
It appears that the current "config" script relies on Unix-specific shell commands (`export`, `chmod`, `./env.sh`, `cp`) that may not work as expected on Windows environments. To address this compatibility issue on Windows, consider using the `configGenerator.js` script, which provides a cross-platform solution for generating configuration files.

The `configGenerator.js` script uses JavaScript and Node.js APIs to achieve the same functionality without relying on shell-specific commands. This approach should work seamlessly on both Unix-like systems and Windows.

Here's how you can proceed:

1. **Rename the Script:**
   If you haven't already, rename the existing script from `"config"` to something else (e.g., `"config-old"`) in the "scripts" section of your `package.json` file. This is to keep it as a reference.

   ```json
   "scripts": {
       "config-old": "export $(grep -v '^#' .env) && chmod +x ./env.sh && ./env.sh && cp config.json ./public/",
       // ...
   }


Add New Script:
Add a new script named "config" that uses the configGenerator.js script instead. This script can be cross-platform and should work on both Windows and Unix-like systems.

"scripts": {
    "config": "node configGenerator.js --templateFileName=config.template.json --outConfigPath=./public",
    // ...
}


Refactor configGenerator.js:
Ensure that the configGenerator.js script is designed to be cross-platform and compatible with both Windows and Unix-like systems. This script should use Node.js APIs for file operations and other functionalities.

For example, the configGenerator.js script can be used as follows:

```
/* eslint-env node */
import fs from 'fs';
import path from 'path';
import yargs from 'yargs';
import dotenv from 'dotenv';
import { fileURLToPath } from 'url';
import { dirname } from 'path';

// Get the directory name and filename
const currentDir = dirname(fileURLToPath(import.meta.url));
const envFilePath = path.join(currentDir, '.env');

try {
  // Read the environment variables from .env file
  const envFile = fs.readFileSync(envFilePath);
  const envVariables = dotenv.parse(envFile);

  // Ensure required environment variables are present
  const requiredEnvVars = ['CLIENT_ID','APP_API_BASE_URL']; // Load from a config file for flexibility
  for (const varName of requiredEnvVars) {
    if (!(varName in envVariables)) {
      handleError(`Required environment variable "${varName}" not found.`);
    }
  }

  // Read the command line arguments
  const argv = yargs(process.argv).argv;
  const { templateFileName, outConfigPath, configFileName = 'config.json' } = argv;

  // Validate and construct file paths
  if (!templateFileName || !outConfigPath) {
    handleError(`Missing required command line arguments.`);
  }

  const templateFilePath = path.join(currentDir, templateFileName);
  const outConfigFilePath = path.join(outConfigPath, configFileName);
  const currentConfigFilePath = path.join(currentDir, configFileName);

  // Check if template file exists
  if (!fs.existsSync(templateFilePath)) {
    handleError(`Template file "${templateFileName}" does not exist.`);
  }

  // Read the template file
  const templateData = fs.readFileSync(templateFilePath, 'utf-8');

  // Replace the placeholders with environment variables
  const substitutedData = templateData.replace(/\$(\w+)/g, (_, key) => {
    return envVariables[key] || '';
  });

  // Write the substituted data to config.json
  try {
    fs.writeFileSync(currentConfigFilePath, substitutedData, 'utf-8');
    console.log('Configuration file written in current directory.');

    // Copy config.json to the public directory
    try {
      fs.copyFileSync(currentConfigFilePath, outConfigFilePath);
      console.log('Configuration file copied to public directory.');
    } catch (copyError) {
      handleError(`Error copying config file: ${copyError.message}`);
    }
  } catch (writeError) {
    handleError(`Error writing config file: ${writeError.message}`);
  }

} catch (error) {
  handleError(`An error occurred: ${error.message}`);
}

function handleError(message) {
  console.error(message);
  process.exit(1);
}
```


With this approach, the "config" script should work seamlessly on both Windows and Unix-like systems, offering a more robust and cross-platform solution for generating configuration files.

Please test the updated "config" script on both Windows and Unix-like systems to ensure its compatibility and correctness.

**Comment by Yogi-Vishwas** [comment]
I have tested the proposed solution and configGenerator.js works just fine.
Thanks.
