### ISSUE TITLE
Integrate SonarCloud for Code Quality Analysis

### ISSUE THREAD

**Issue by rohit-sourcefuse** [sourcefuse/react-boilerplate-ts-ui#64]
**Overview:**
The react-boilerplate-ts-ui repository currently lacks integration with SonarCloud, a powerful code quality analysis tool. SonarCloud provides insights into code quality, security vulnerabilities, and technical debt, helping ensure the maintainability and robustness of the codebase.

**Issue Details:**
While the repository offers a solid foundation for development, the absence of SonarCloud integration limits the ability to perform in-depth code quality analysis and identify potential issues early in the development lifecycle.

**Proposed Solution:**
To enhance the codebase's quality and maintainability, it's recommended to integrate SonarCloud into the repository's CI/CD pipeline. This integration will enable automated code analysis, security vulnerability detection, and code smells identification.

**Steps to Integrate SonarCloud:**

1. **Create a SonarCloud Account:** If not already done, create an account on SonarCloud (or use an existing account) and obtain the required authentication token.

2. **Configure SonarCloud on the Repository:** Add the necessary SonarCloud configuration files to the repository (e.g., sonar-project.properties).
Configure the project's settings in the SonarCloud dashboard to match the repository's structure and technology stack.

3. **Integrate SonarCloud into CI/CD Pipeline:** Modify the repository's CI/CD pipeline configuration (e.g., GitHub Actions, Travis CI, etc.) to trigger code analysis on each build. Use the SonarCloud CLI or appropriate integration to send analysis results to SonarCloud.

4. **View and Address Findings:** Monitor the SonarCloud dashboard for code quality, security vulnerabilities, and technical debt findings. Address the identified issues by following SonarCloud's recommendations and best practices.

**Expected Benefits:**
Integrating SonarCloud will provide the following benefits:

Early detection of code quality issues, security vulnerabilities, and technical debt.
Improved maintainability, robustness, and readability of the codebase.
Enhanced developer productivity and collaboration through actionable insights.

**Environment:**

Operating System: N/A
CI/CD Tool: AWS CodePipeline

**Comment by shubhamp-sf** [comment]
@samarpan-b sir can we please on-board this repo to sonarcloud?
